sudo: required
services:
  - docker

before_install:
  - docker build -t ubersensei/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ubersensei/react-test npm test -- --coverage

after_success:
  - docker build -t ubersensei/multi-client ./client
  - docker build -t ubersensei/multi-nginx ./nginx
  - docker build -t ubersensei/multi-server ./server
  - docker build -t ubersensei/multi-worker ./worker
  # Login to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ubersensei/multi-client 
  - docker push ubersensei/multi-nginx 
  - docker push ubersensei/multi-server 
  - docker push ubersensei/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-922767242623
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: $AWS_SECRET_KEY
